spring:
  profiles:
    active:
  - dev

---
server:
  port: 8005
spring:
  profiles: dev
  application:
    name: wen
eureka:
  client:
    service-url:
    defaultZone: http://localhost:7001/eureka/
